### ISSUE TITLE
Error when trying to log key rotation

### ISSUE THREAD

**Issue by sphen13** [grahamgilbert/crypt#47]
On test build linked #42 

When checkin rotated the key because it was used there is a logging error.  rotation and checkin all work as expected.

```bash-3.2# /Library/Crypt/checkin
OutputPath Pref is set to: /private/var/root/crypt_output.plist
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file checkin, line 209
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file checkin, line 209
Attempting to rotate Recovery Key.
Recovery Key rotated.
Key escrow successful.
Successfully escrowed key.
```

**Comment by grahamgilbert** [comment]
On which operating system?

**Comment by sphen13** [comment]
10.12.6

**Comment by grahamgilbert** [comment]
And the exact build used? That package has been updated five times over the last few days.

**Comment by sphen13** [comment]
tried to link that to this thread -- it was the specific build linked from issue 42 and one that you were requesting feedback from in slack:
https://dl.dropboxusercontent.com/u/27235/Crypt-2.3.0.79.pkg

**Comment by grahamgilbert** [comment]
That's an old build now, I'm pretty sure this has been fixed. Please post your crypt_output.plist so I can confirm.

**Comment by sphen13** [comment]
ill try an updated build and let you know:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Change</key>
	<true/>
	<key>EnabledDate</key>
	<string>2017-07-31 20:38:44 -0700</string>
	<key>EnabledUser</key>
	<string>sphen</string>
	<key>HardwareUUID</key>
	<string>564D990E-5617-7FFC-48BC-C6FBA2D3C1FA</string>
	<key>RecoveryKey</key>
	<string>L9ZF-TMWX-E64H-M6UN-LVOJ-4OBP</string>
	<key>SerialNumber</key>
	<string>VMSqklh8UxVg</string>
	<key>escrow_success</key>
	<true/>
	<key>last_run</key>
	<date>2017-08-01T03:38:45Z</date>
</dict>
</plist>
```

**Comment by sphen13** [comment]
i dont currently have an id capable of code signing...

**Comment by weswhet** [comment]
I can reproduce this. It's an error with the logging call.
```>>> key_path = '/var/root/crypt_output.plist'
>>> logging.warning(syslog.LOG_ALERT, 'Could not locate {0}'.format(key_path))
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file <stdin>, line 1
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file <stdin>, line 1
```

I'll fix it.

**Comment by weswhet** [comment]
FYI @erikng This logging call throws the above Traceback. Just in case you use something similar elsewhere. 

```
logging.warning(syslog.LOG_ALERT, 'Could not locate {0}'.format(key_path))
```
